### ISSUE TITLE
PSK - NULL Cipher suite support requires 

### ISSUE THREAD

**Issue by thiyaneshece** [gesslerpd/pyopenssl-psk#4]
I could see that this library provides below cipher suites for SSL/TLS communication between client and server

TLS_AES_256_GCM_SHA384', 'TLS_CHACHA20_POLY1305_SHA256', 'TLS_AES_128_GCM_SHA256', 'PSK-AES128-GCM-SHA256'

Whereas i would like to set **TLS_PSK_WITH_NULL_SHA256 (0x00b0)** cipher suite, but i could not, since it is not available.

Please correct me , if my understanding is incorrect ? am i missing anything to set this cipher suite ? 

Is there a possible way to extend this library to support PSK NULL Cipher Suites, if not supported now?

**Comment by gesslerpd** [comment]
This library patches pyOpenSSL to add an interface for the PSK related features of openssl.

So this library only supports what is supported by the version of openssl used to build the pyOpenSSL python library.

Some ciphers may be supported but not enabled by default because they pose security risk.

This link from openssl talks about a special cipher string syntax that will also set the openssl security level.

https://www.openssl.org/docs/man1.1.0/man1/ciphers.html

For example, this lowers the security level of openssl to 0 and may allow the use of Null ciphers.

```
ctx.set_cipher_list(b'<your set of ciphers>:@SECLEVEL=0')
```

**Comment by thiyaneshece** [comment]
@gesslerpd Thanks for the explanation and clarification .  
I have tried to setup "PSK_NULL_CIPHER" as mentioned above, it worked straight away. 
Thanks again.:)
