### ISSUE TITLE
Does the library supports TLSv1.3

### ISSUE THREAD

**Issue by thiyaneshece** [gesslerpd/pyopenssl-psk#7]
I'm using this library for secure subscribe and unsubscribe method between client and server that uses the cipher suites 'PSK_NULL_SHA256 and PSK_AES128_GCM_SHA256' in websocket communication using TLSv1_2.

I would like to use the same approach in TLSv1_3. 
@gesslerpd  do you have any suggestions or plan to support this library for newer version of TLSv1_3?

**Comment by gesslerpd** [comment]
There is a good table at this link showing the TLS protocol version constants https://docs.python.org/3/library/ssl.html#ssl.SSLContext

There's also a footnote there that states the following:

> TLS 1.3 protocol will be available with PROTOCOL_TLS in OpenSSL >= 1.1.1. There is no dedicated PROTOCOL constant for just TLS 1.3.

Since OpenSSL and the binding library supports this it should work and be configured as stated in this issue: pyca/pyopenssl#996
